SUSE-Enceladus/cgyle

cgyle/cli.py
cgyle/proxy.py
package/python-cgyle-spec-template
pyproject.toml
test/unit/cli_test.py
test/unit/proxy_test.py
test/unit/test_helper.py

Using the option setting --updatecache local://distribution:DIR allows to create a local cache in the format of the 'distribution' registry to allow preserving the data tree of this server

Add support for local registry cache

---

cgyle/catalog.py
cgyle/cli.py
test/unit/cli_test.py

Add new option --skip-policy-section which can be specified multiple times and only in combination with --policy-file. The provided section names are excluded from the policy file handling if present

Add support for skipping policy sections

---

cgyle/catalog.py
test/data/policy.test
test/unit/catalog_test.py

The current glob to regexp translation assumes a one-or-more match which is not necessarily correct. This commit fixes it and adds a test case with data from the SCC team.

Fix policy glob match

---

cgyle/cli.py
cgyle/exceptions.py
cgyle/proxy.py
test/unit/cli_test.py
test/unit/proxy_test.py

This allows to pass login credentials for the proxy registry. In case an authentication to the proxy registry server is required these credentials are used prior any pull from the proxy.

Add --proxy-creds commandline option

---

package/python-cgyle-spec-template

The psutil module requirement is listed in the pyproject.toml but was forgotten in the package spec. This commit fixes it

psutil is required but was not added to the spec

---

cgyle/cli.py

Allow to specify the maximum number of parallel container caching requests. Please note all tags of a container are sequentially handled in one request.

Add option --max-requests

---

cgyle/proxy.py

When creating a local output cache make sure to capture IOError's e.g permission denied as possible error caused by that action and report them with a useful error message instead of a stack trace

Capture IOErrors as known error for local: target

---

package/python-cgyle-spec-template
pyproject.toml
systemd/registry-suse-com.service
systemd/registry-suse-com.timer

Add systemd unit to run cgyle in local sync mode for a suse policy based sync from registry.suse.com into the default storage space of the distribution server below /var/lib/registry

Added timer unit and service for registry.suse.com

---

cgyle/catalog.py
cgyle/cli.py
cgyle/credentials.py
cgyle/proxy.py
test/data/credentials
test/unit/credentials_test.py

Allow options --registry-creds/--proxy-creds to read from file. If the given value is a file in the system it will be used and read as a yaml file in the format of the rmt.conf file

Support reading credentials from file

---

systemd/registry-suse-com.service

Instead of passing user:pass credentials information on the commandline, use the /etc/rmt.conf file as input source for the credentials

Read credentials from file for SUSE service

---

systemd/registry-suse-com.service

The SUSE cgyle service is expected to run as user _rmt

Run SUSE service as user _rmt and group nginx

---

cgyle/cli.py
cgyle/proxy.py
test/unit/cli_test.py

cgyle only keeps the log files of failed caching attempts and wipes the successful ones because there is no meaningful information in a successful caching process other than, the container was cached, which is an information that is still present by reading the log directory tree. The error information from all failed log files will now also be combined into one log file and appended to an eventually existing file.

Collect error logs into one file

---

package/python-cgyle-spec-template

podman and skopeo has changed caller semantics in the past. Make sure a workable version is required by the package

Added min version requirements

---

cgyle/proxy.py
test/unit/proxy_test.py

Write log file of the registry server running inside of the container when using the local://distribution feature on the host as `/var/log/cgyle_proxy.log`

Expose registry instance log data

---

README.rst
cgyle/proxy.py
package/python-cgyle-spec-template
test/unit/proxy_test.py

When using cgyle in local://distribution mode, we run a container formerly named docker.io/library/registry:latest. If this container does not exist it will be fetched from the network. However, there are regions which doesn't allow this type of network access. To decouple the loading from the network we packaged the container, required it here in the spec for cgyle and referenced the container only as registry:latest.

Decouple use of registry container from network

---

cgyle/proxy.py
test/unit/proxy_test.py

skopeo may end up in an endless loop attempting to copy a specific container. This creates a problem in an automated environment such as cgyle potentially causing endless runtime. We limit the number of attempts we let skopeo take to copy a given container to 5. This allows us to move on and copy other containers. The next time cgyle runs we will try the previously failed container again.

Limit the number of copy tries

---

cgyle/proxy.py
systemd/registry-suse-com.service
test/unit/proxy_test.py

The sync process is run by a timer of 6h at the moment. If the service is still running when the timer kicks in, no restart will happen. In cgyle each container is fetched by its own skopeo copy process. We found situations in which that copy process receives an error and reconnects in a loop forever. As of today there is no way to tell skopeo to stop this iteration after some time and I also believe there is a bug in skopeo causing this because a simple restart of the cgyle service fixes the issue. For us it's important that the cgyle process is not blocked forever. Thus this commit suggest a max runtime controlled by systemd of 5h.

Make sure cgyle runtime is limited

---

systemd/registry-suse-com.service
systemd/registry-suse-com.timer

The infrastructure runs several network bandwidth consuming processes potentially at the same time. To avoid this add a random delay on the timer. In addition we found that the hard stop in the service file hits us in the production environment. Let's add a restart condition on failure for  this case too

Prevent thundering herd condition

---

systemd/registry-suse-com.service

Older versions of podman uses the /tmp directory for the runroot of the rootless podman storage. This causes an issue if there are runtime artifacts from older container instances left on the system. To avoid a service startup error this commit adds a pre step to the systemd service which removes any stale /tmp/containers-user-ID directory.

Added a runtime cleanup prior service startup

---

systemd/registry-suse-com.service

For testing high load situations make sure there is only one active skopeo process

Reduce max-requests to 1

---

cgyle/cli.py
cgyle/proxy.py
test/unit/cli_test.py
test/unit/proxy_test.py
tools/suse2ecr

Attestation tags (.att) are used to provide SBOM information for containers. By default we do not sync them. The new
option --with-attestation allows to turn it on

Allow sync of attestation tags
